version: '3.7'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
     - ./.env
    ports:
      - "5432:5432"
  api:
    build:
      context: ./
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    container_name: api
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - ./:/usr/shopping-list/api
    ports:
      - "4000:4000"
    depends_on:
      - postgres-db
    env_file:
      - ./.env

volumes:
  postgres-data:
    name: postgres-data